[mypy]
python_version = 3.13
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
ignore_missing_imports = True

# Módulos a chequear con type hints
[mypy-src.vector]
disallow_untyped_defs = True

[mypy-src.ray]
disallow_untyped_defs = True

[mypy-src.utils.*]
disallow_untyped_defs = True
